name: cine_me
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

useMaterial3: true

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.3
  shared_preferences: ^2.1.0
  http: ^0.13.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  meta: ^1.7.0
  crypto: ^3.0.2
  device_info_plus: ^8.2.1
  get_it: ^7.3.0
  carousel_slider: ^4.2.1
  palette_generator: ^0.3.3+2
  beamer: ^1.5.3
  intl: ^0.18.1
  go_router: ^7.0.0
  flutter_inappwebview: ^5.7.2+3
  youtube_player_flutter: ^8.1.2
  masked_text: ^1.1.2
  barcode_widget: ^2.0.3
  share_plus: ^6.3.4
  flutter_launcher_icons: ^0.13.1
  rxdart: ^0.27.7
  dio: ^5.1.2
  flutter_animate: ^4.1.1+1
  icons_flutter: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/img.png
    - assets/images/img.jpg
    - assets/images/error.png
    - assets/images/logo.png

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt/Prompt-Black.ttf
        - asset: assets/fonts/Prompt/Prompt-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/Prompt/Prompt-Regular.ttf
          weight: 200
    - family: NotoSansDisplay
      fonts:
        - asset: assets/fonts/Noto_Sans_Display/static/NotoSansDisplay-Regular.ttf